# Generated by Django 4.0.1 on 2022-01-31 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('CodeE', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NomE', models.CharField(max_length=50)),
                ('PrenomE', models.CharField(max_length=50)),
                ('GradeE', models.CharField(max_length=50)),
                ('TelE1', models.CharField(max_length=10, null=True)),
                ('TelE2', models.CharField(blank=True, max_length=10, null=True)),
                ('EmailE', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=50)),
                ('E_domaine', models.CharField(max_length=50)),
                ('email_E', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('NTel1', models.CharField(max_length=10, null=True)),
                ('NTel2', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('J_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('Enseignants', models.ManyToManyField(to='app.Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Membre_Entreprise',
            fields=[
                ('CodeM', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NomP', models.CharField(max_length=50)),
                ('PrenomP', models.CharField(max_length=50)),
                ('GradeP', models.CharField(max_length=50)),
                ('TelP1', models.CharField(max_length=10, null=True)),
                ('TelP2', models.CharField(blank=True, max_length=10, null=True)),
                ('EmailP', models.EmailField(max_length=254, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('spceciality', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('Tel1', models.CharField(max_length=10, null=True)),
                ('Tel2', models.CharField(blank=True, max_length=10, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme', models.CharField(max_length=50)),
                ('Period', models.CharField(max_length=50)),
                ('Date_Deb', models.DateField()),
                ('Date_Fin', models.DateField()),
                ('domaine', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Ouvrier', '1- Stage Ouvrier'), ('Court', '2- Stage Court durée'), ('PFE', "3- Stage fin d'étude (PFE)")], max_length=100)),
                ('Rapport', models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%D')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.enseignant')),
                ('mmbr_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membre_entreprise')),
                ('soutenire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jury')),
                ('stagiaires', models.ManyToManyField(related_name='stages', to='app.Stagiaire')),
            ],
        ),
        migrations.AddField(
            model_name='jury',
            name='Membre_Entreprises',
            field=models.ManyToManyField(to='app.Membre_Entreprise'),
        ),
    ]
