# Generated by Django 4.0.1 on 2022-02-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='matricule',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
